### ISSUE TITLE
Validate server protocol

### ISSUE THREAD

**Issue by jnhmn** [d120/pyTUID#1]
Please validate, if CAS is the appropriate protocol for this usecase.

In long term, CAS 1.0 and 2.0 seem to be replaced by SAML 1.1

Source: https://www.hrz.tu-darmstadt.de/id/authentisierung/sso/fradministratoren/inh_cas_protokoll.de.jsp

**Comment by schroedingersZombie** [comment]
For the moment CAS2 with SAML should work.
I'll look into it, when it is more urgent.
