### ISSUE TITLE
Complete setup.py

### ISSUE THREAD

**Issue by exploide** [d120/pyTUID#3]
`setup.py` contains some dummy statements like url, long_description and license. The latter would require to actually choose a license, and add the proper text file to the repository. This would be nice because other projects at university might want to use this.

**Comment by jnhmn** [comment]
I don't think, that the AGPL is the right thing here...

"    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
invalidate such permission if you have separately received it."

This may prevent others from using this.
