### ISSUE TITLE
Increase maxsize of groups field

### ISSUE THREAD

**Issue by exploide** [d120/pyTUID#8]
It turns out that the CAS groups of someone, probably due to his many master programs, don't fit the size of the groups column. Hence he is not able to login and a corrupted database entry is created.

/cc @MuellerMaximilian ... war ja klar 😉

**Comment by ckleemann** [comment]
You should not use a size limited CharField at all for the group Information. There is no upper boundary for the size of this field! Better use a TextField instead.
